"""create cached_routes table

Revision ID: f2f1627c4671
Revises: 
Create Date: 2026-07-11 22:30:38.570952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f1627c4671'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('origin_lng', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('dest_lat', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('dest_lng', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('travel_mode', sa.String(length=20), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cached_route_lookup', 'cached_routes', ['origin_lat', 'origin_lng', 'dest_lat', 'dest_lng', 'travel_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cached_route_lookup', table_name='cached_routes')
    op.drop_table('cached_routes')
    # ### end Alembic commands ###
